/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg8.bit.work.space;

/**
 *
 * @author Grant Ivan
 */
public class Test extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Test.class.getName());

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReenPass = new javax.swing.JLabel();
        lblFirst = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        lblLast = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        lblDesUser = new javax.swing.JLabel();
        lblDesPass = new javax.swing.JLabel();
        txtDesPass = new javax.swing.JPasswordField();
        txtReenPass = new javax.swing.JPasswordField();
        txtDesUser = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReenPass.setFont(new java.awt.Font("Pixelify Sans", 1, 12)); // NOI18N
        lblReenPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pass_Icon.png"))); // NOI18N

        lblFirst.setFont(new java.awt.Font("Pixelify Sans", 1, 12)); // NOI18N
        lblFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User_Icon2.png"))); // NOI18N

        txtFirst.setBorder(null);
        txtFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstActionPerformed(evt);
            }
        });

        lblLast.setFont(new java.awt.Font("Pixelify Sans", 1, 12)); // NOI18N
        lblLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User_Icon2.png"))); // NOI18N

        txtLast.setBorder(null);

        lblDesUser.setFont(new java.awt.Font("Pixelify Sans", 1, 12)); // NOI18N
        lblDesUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/User_Icon.png"))); // NOI18N

        lblDesPass.setFont(new java.awt.Font("Pixelify Sans", 1, 12)); // NOI18N
        lblDesPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pass_Icon.png"))); // NOI18N

        txtDesPass.setBorder(null);
        txtDesPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesPassActionPerformed(evt);
            }
        });

        txtReenPass.setBorder(null);
        txtReenPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReenPassActionPerformed(evt);
            }
        });

        txtDesUser.setEditable(false);
        txtDesUser.setBackground(new java.awt.Color(244, 247, 247));
        txtDesUser.setText("Enter username");
        txtDesUser.setBorder(null);
        txtDesUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesUserActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(244, 247, 247));
        btnCreate.setForeground(new java.awt.Color(48, 48, 72));
        btnCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Button1.png"))); // NOI18N
        btnCreate.setText("Create");
        btnCreate.setBorder(null);
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLast)
                    .addComponent(lblDesUser)
                    .addComponent(lblDesPass)
                    .addComponent(lblReenPass)
                    .addComponent(lblFirst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesUser, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesPass, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReenPass, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(265, 265, 265))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 576, Short.MAX_VALUE)
                    .addComponent(btnCreate)
                    .addGap(38, 38, 38)
                    .addComponent(btnCancel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDesUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDesPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblReenPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReenPass))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(422, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCreate)
                        .addComponent(btnCancel))
                    .addGap(0, 15, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDesPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesPassActionPerformed

    private void txtDesUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesUserActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String desUser = txtDesUser.getText().trim();
        char[] desPass = txtDesPass.getPassword();
        String desPassConv = new String(desPass);
        char[] reenPass = txtReenPass.getPassword();
        String desReenPassConv = new String(reenPass);
        String first = txtFirst.getText().trim();
        String last = txtLast.getText().trim();

        if (desUser.isEmpty() || desPassConv.isEmpty() || desReenPassConv.isEmpty() || first.isEmpty() || last.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fill-in all fields!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else {
            if (!(desPassConv.equals(desReenPassConv))){
                JOptionPane.showMessageDialog(null, "Passwords are not the same!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else{
                Users user = new Users(desUser, desPassConv, first, last);

                users.add(user);

                saveUser();
            }
        }

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        new Login().setVisible(true);

    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtReenPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReenPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReenPassActionPerformed

    private void txtFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Test().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel lblDesPass;
    private javax.swing.JLabel lblDesUser;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblReenPass;
    private javax.swing.JPasswordField txtDesPass;
    private javax.swing.JTextField txtDesUser;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    private javax.swing.JPasswordField txtReenPass;
    // End of variables declaration//GEN-END:variables
}
